// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIuEqAgRNcKug0PkgYumoGSBtsEo_S7kM',
    appId: '1:31316772176:web:cb2b044c5173549a3b1855',
    messagingSenderId: '31316772176',
    projectId: 'vayufy-ece2d',
    authDomain: 'vayufy-ece2d.firebaseapp.com',
    storageBucket: 'vayufy-ece2d.firebasestorage.app',
    measurementId: 'G-Z7NY733SCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxFmZaWqvaGJ8ONZ4i-KtAFevs9EXxu-8',
    appId: '1:31316772176:android:904bdc4bc95845773b1855',
    messagingSenderId: '31316772176',
    projectId: 'vayufy-ece2d',
    storageBucket: 'vayufy-ece2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0gtQrPpnJvkvFnk6if1fM42ZKl4KBYE0',
    appId: '1:31316772176:ios:bb465386aacb007e3b1855',
    messagingSenderId: '31316772176',
    projectId: 'vayufy-ece2d',
    storageBucket: 'vayufy-ece2d.firebasestorage.app',
    iosBundleId: 'com.example.vayufy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0gtQrPpnJvkvFnk6if1fM42ZKl4KBYE0',
    appId: '1:31316772176:ios:bb465386aacb007e3b1855',
    messagingSenderId: '31316772176',
    projectId: 'vayufy-ece2d',
    storageBucket: 'vayufy-ece2d.firebasestorage.app',
    iosBundleId: 'com.example.vayufy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIuEqAgRNcKug0PkgYumoGSBtsEo_S7kM',
    appId: '1:31316772176:web:0aeb371c11de8a933b1855',
    messagingSenderId: '31316772176',
    projectId: 'vayufy-ece2d',
    authDomain: 'vayufy-ece2d.firebaseapp.com',
    storageBucket: 'vayufy-ece2d.firebasestorage.app',
    measurementId: 'G-GYMYH5E5LJ',
  );
}
